server:
  port: 12581
spring:
  application:
    name: crm-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:12580/eureka
zuul:
  prefix: /api
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 3500
  MaxAutoRetriesNextServer: 0
  MaxAutoRetries: 0
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 5000